### ISSUE TITLE
Quotes converted wrongly

### ISSUE THREAD

**Issue by jodros** [Omikhleia/markdown.sile#137]
The language is set to Portuguese, but the quotes "" are being converted to «».

Maybe it's taking the system's locale, in Russian, into account?

**Comment by Omikhleia** [comment]
Portuguese from Portugal (a.k.a. "pt") uses these quotes, there's nothing
wrong here.

Checking smartquotes.sile (the module at stake here), there's a specific
rule for "pt-BR". Maybe that's what you want? (And no, the module doesn't
make any assumption on a system locale)


Le mar. 24 déc. 2024, 23:35, João A. Quinaglia ***@***.***> a
écrit :

**Comment by jodros** [comment]
Worked!
