### ISSUE TITLE
Should we include an `outputter` that would just write out the output from `inputter.markdown.parse(…)`?

### ISSUE THREAD

**Issue by ctrlcctrlv** [Omikhleia/markdown.sile#15]
I added a debug locally to do it but it seems highly useful as most likely some people will want to go from Markdown to SILE on a more permanent basis.

```  diff lua
diff --git a/inputters/markdown.lua b/inputters/markdown.lua
index 980e97e..8d15216 100644
--- a/inputters/markdown.lua
+++ b/inputters/markdown.lua
@@ -3,6 +3,7 @@
 -- Using the lunamark library.
 --
 local utils = require("packages.markdown.utils")
+local ast = require("sile.core.ast")
 
 local function simpleCommandWrapper (name)
   -- Simple wrapper argound a SILE command
@@ -334,6 +335,7 @@ function inputter.parse (_, doc)
     escaped_line_breaks = true,
   })
   local tree = parse(doc)
+  SU.debug("markdown", "Parsed tree: " .. ast.astToSil(tree))
   -- The Markdown parsing returns a string or a SILE AST table.
   -- Wrap it in some document structure so we can just process it, and if at
   -- root level, load a default support class.
```

**Comment by Omikhleia** [comment]
Heh you found my little undocumented "core.ast" hack :)

That's something I quickly added here for my own debug initially, but yes I had that in mind, In my local SILE it have it as a "fake" backend. I need to iron it out, though, and ensure round-tripping works (i.e. processing the output AST again gives the exact same result). It should not be part of this package IMHO, but go into the standard SILE distribution, so it would be available for any inputter.

I am ok with an issue ticket here, though, as a reminder for me to eventually refactor that part in a cleaner way and make a PR to SILE.

**Comment by Omikhleia** [comment]
> (...) as most likely some people will want to go from Markdown to SILE on a more permanent basis.

The more things I do with SILE, the less I use its SIL language, except for very low-level things (with lots of `%` to be safe) and quick tests...

SIL has long-standing unaddressed issues with spacing and paragraphing -- it's somewhat bogus and defective.

I don't think it's "most likely" that undefined people will want to go from an input format to SIL on a more permanent basis for any _good_ reason. It's an illusion. I can be wrong in these views, but I am heading in other directions.

Therefore the "AST to SIL" debug hack here cannot have a true "round-trip" in the current state of art, and I don't use it. It will go away in the next release of **markdown.sile**.
