### ISSUE TITLE
Djot and Lunamark vendored copies should eventually be dependencies

### ISSUE THREAD

**Issue by ctrlcctrlv** [Omikhleia/markdown.sile#16]
Or else just a patch application. :-)

**Comment by Omikhleia** [comment]
Or a luarocks dependency, eventually.

**Comment by Omikhleia** [comment]
Also for now, having our 'vendored' version allows experimenting things quickly, before PR's to Lunamark are iron-proofed and accept. This doesn't fully avoid issue (e.g. #11), but that's acceptable to a certain point => Non-urgent milestone.

**Comment by Omikhleia** [comment]
Generalized the topic description. We are still in advance with changes on both modules.
So this is probably not going to be different anytime soon (and is _very_ low priority anyway)

**Comment by Omikhleia** [comment]
Rejecting:
 - The README says it ("eventually")
 - I don't have any plans towards it, as long as the "vendored" modules don't significantly improve, which is beyond my reach.
